services:
  ftm-heal:
    build:
      context: .
      args:
        SONIC_VERSION: ${SONIC_VERSION}
    image: ftm-node:${SONIC_VERSION}
    container_name: ftm-heal
    mem_limit: 32g
    command: ["/app/sonictool", "--datadir=${DATADIR}", "--cache=${CACHE_MB}", "heal"]
    environment:
      - GOMEMLIMIT=32GiB
    volumes:
      - "${HOME}/.sonic:${DATADIR}"
    network_mode: host
