services:
  linea:
    image: nethermind/nethermind:${NETHERMIND_VERSION}
    container_name: linea-el
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    stop_grace_period: 120s
    volumes:
      - ${HOME}/linea_data:${DATADIR}
    network_mode: host
    command:
      - --datadir
      - ${DATADIR}
      - --config
      - linea-mainnet
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=${HTTP_ADDR}
      - --JsonRpc.Port=${HTTP_PORT}
      - --JsonRpc.WebSocketsPort=${WS_PORT}
      - --Network.P2PPort=${P2P_PORT}
      - --Metrics.Enabled=true
      - --Metrics.ExposePort=${METRICS_PORT}