services:
  sonic:
    build:
      context: .
      args:
        SONIC_VERSION: ${SONIC_VERSION}   # <--- bump here when you need a new version - used for BUILD
    image: sonic-node:${SONIC_VERSION}      # <--- change the image tag here - used for RUN
    container_name: sonic
    restart: unless-stopped
    mem_limit: 32g
    stop_grace_period: 120s
    command:
      - "--datadir=${DATADIR}"
      - "--http"
      - "--http.addr=${HTTP_ADDR}"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--http.api=${HTTP_API}"
      - "--http.port=${HTTP_PORT}"
      - "--ws"
      - "--ws.addr=${WS_ADDR}"
      - "--ws.origins=*"
      - "--ws.api=${WS_API}"
      - "--ws.port=${WS_PORT}"
      - "--cache=${CACHE_MB}"
      - "--nat=extip:${EXT_IP}"
      - "--maxpeers=${MAX_PEERS}"
      - "--rpc.gascap=${GAS_CAP}"
      - "--rpc.txfeecap=${TX_FEE_CAP}"
    volumes:
      - "${HOME}/.sonic:${DATADIR}"
    network_mode: host